### ISSUE TITLE
Duplicate Copies of GHC

### ISSUE THREAD

**Issue by StevenXL** [asdf-community/asdf-haskell#18]
Hi Folks,

I apologize if this is either not the right forum for this question, or if the problem is due to user error.

However, I have installed `asdf-vm` and `asdf-haskell`, and I have installed `ghc-8.6.5` by running `asdf install haskell 8.6.5`. I believe the install went fine. I went into my `~/.asdf/installs/haskell`, and could see the `8.6.5` folder in there. I used `stack install hlint` and I could see that `which hlint` point to an asdf shim; and did `which stack` also pointed to an asdf shim. All of this is to say that `asdf-vm` and `asdf-haskell` seemed to have been installed properly. 

However, when I go into a project that uses the lts-14.7 (which, in turn, uses ghc 8.6.5), and I run `stack test`, then the same ghc version is downloaded again into a `~/.stack` folder. 

Is my configuration wrong? Shouldn't it be using the ghc already in `~/.asdf`?

**Comment by StevenXL** [comment]
I'm guessing one way to integrate this is to use the `STACK_ROOT` environmental variable as described [here](url) (and more background info [here](https://github.com/commercialhaskell/stack/issues/1178)). Should I add this to the documentation?

**Comment by vic** [comment]
Looks like we should be exporting that variable from a `bin/exec-env`. 


If anyone is willing to submit a PR, it would be more than welcome.

Here's a link to the documentation:
https://asdf-vm.com/#/plugins-create?id=binexec-env

**Comment by StevenXL** [comment]
@vic  it looks like this started happening when I switched from version `2.1.3` of stack to `2.3.1`.
